### ISSUE TITLE
Method request: Recursive Feature Elimination for Support Vector Machines

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3fselect#1] opened 2019-06-21 13:40 UTC
"This embedded method uses the current set of features to train an SVM classifier iteratively by removing the least important features, as indicated by the weights in the SVM solution."

Seijo-Pardo, B., Porto-Díaz, I., Bolón-Canedo, V., & Alonso-Betanzos, A. (2017). Ensemble feature selection: Homogeneous and heterogeneous approaches. Knowledge-Based Systems, 118, 124–139. https://doi.org/10/f9qgrv

**Comment by be-marc** [comment] 2019-12-06 12:56
RFE is now implement in `mlr3fselect`. It should work with SVM when the `importance` method is implemented for this learner.

**Comment by philipp-baumann** [comment] 2020-08-27 16:53
Hi mlr3 team. Awesome, the `FSelectorRFE` method is a very useful addition to the mlr3fselect toolbox, particularly in combination with `AutoFSelect` and nested resampling to avoid selection bias. To rank importance of spectrum features with high degree of collinearity, I typically remove variables in batches to achieve predefined variable subset sizes (error assessment on outer CV resamples). (Until now I have been observing mlr3 from the outside and haven't applied it yet because PLS regression and Cubist learners are not yet wrapped, and did not yet find the time to dive further into concepts and eventually contribute).

The current version only supports one-by-one removal of unimportant variables. Have you by change planned to augment the functionality of `FSelectorRFE` to enable predefined subset sizes as inputs (i.e., remove batches of variables)? 

That would be very useful I think since nested resampling with e.g. rule-based learning on many variables/larger libraries and decent hyperparameters is computationally relatively expensive. I so far used used a custom implementation with caret to achieve this (e.g., [this gist](https://gist.github.com/philipp-baumann/e4404ca0ce3c83edb92dc2199150007b); 5 times 10-fold group CV on outer `fold_idx`; there is one for RF in caret outlined [here](https://topepo.github.io/caret/recursive-feature-elimination.html)), but a clean mlr3 solution with RFE variable removal in batches would be much more robust and universal in terms of supporting many more learners, more flexible tuning and resampling setups.

Thanks for the awesome work done in all mlr3 :-)

**Comment by be-marc** [comment] 2020-08-31 11:13
@philipp-baumann Thanks for you interest in mlr3fselect. You can check out #22. I added predefined subset sizes with the `subset_sizes` parameter.

**Comment by philipp-baumann** [comment] 2020-09-02 08:37
Awesome :-) thanks!

**Comment by mllg** [comment] 2020-09-02 10:21
Are fixed subset sizes the usual approach?

**Comment by be-marc** [comment] 2020-09-02 11:17
Fixed number of features to be removed in each iteration and percentage of features seems to be other used options. I think we should support that. But not sure what should be the default at the moment.

**Comment by be-marc** [comment] 2020-10-23 08:00
Default is feature_fraction = 0.5 and min_features = 1. Closed and transferred to https://github.com/mlr-org/mlr3learners/issues/161.

**Closed by be-marc** 2020-10-23 08:00 UTC

**Comment by be-marc** [comment] 2023-05-02 08:05
RFE works now on an SVM https://mlr-org.com/gallery/optimization/2023-02-07-recursive-feature-elimination/#support-vector-machine.
