### ISSUE TITLE
Nested resampling memory allocation

### ISSUE THREAD

**Issue by be-marc** [mlr-org/mlr3fselect#77] opened 2023-02-15 13:57 UTC
This issue belongs to [https://stackoverflow.com/questions/75405217/no-model-stored-with-mlr3/75457848?ß](https://stackoverflow.com/questions/75405217/no-model-stored-with-mlr3/).

We check with a custom learner that allocates memory while training.

```r
library(mlr3verse)
library(mlr3misc)
library(R6)

LearnerClassifMemory = R6Class("LearnerClassifMemory", inherit = LearnerClassifDebug,
    public = list(

      memory = NULL,

      initialize = function(memory) {
        self$memory = memory
        super$initialize()
      }
    ),

    private = list(

      .train = function(task) {

        # allocate memory
        x = runif(self$memory)
        Sys.sleep(5)
        rm(x)

        super$.train(task)
      }
  )
)
```

Test with 8 GB and 10-fold cv.

```r
learner = LearnerClassifMemory$new(memory = 10^9)

rr = resample(tsk("spam"), learner, rsmp("cv", folds = 10))
```

Resampling seems to work. It allocates 8 GB and not 10 * 8 GB.

**Comment by be-marc** [comment] 2023-02-15 14:02
Nested resampling also does not allocate more than 8 GB of memory.

```r
afs = auto_fselector(
  learner = learner,
  resampling = rsmp("cv", folds = 3),
  measure = msr("classif.ce"),
  terminator = trm("evals", n_evals = 10),
  method = "random_search"
)

rr = resample(tsk("spam"), afs, rsmp("cv", folds = 3))
```

**Comment by awaldman000** [comment] 2023-02-15 17:28
Thanks! I've tried this code using RStudio Pro and both calls use the same amount of RAM (~7.7GB). Could it be that setting multiple threads for the learner on my dataset causes the issue? However, I do use the same call to use multiple threads for the learner with both the single model and the nested resampling so I am not sure how that could be the cause of the discrepancy.

**Comment by awaldman000** [comment] 2023-02-15 17:30
Happy to send over the dataset if that would be useful to benchmark?

**Comment by be-marc** [comment] 2023-02-15 18:38
> Thanks! I've tried this code using RStudio Pro and both calls use the same amount of RAM (~7.7GB). I noticed that the RAM being used is not sustained (ie it goes back to baseline afterwards) for the first call and is sustained for the second call.

Yes that is normal. The memory is only freed when new data is written to it. You can manually garbage collect with `gc()`.

**Comment by be-marc** [comment] 2023-02-15 18:41
> Happy to send over my dataset if that would be useful to benchmark?

I will try a large one from openml.

```r
library(mlr3oml)
library(mlr3learners)

task = tsk("oml", data_id = 150)
learner = lrn("classif.ranger", num.trees = 10000, num.threads = 40)

learner$train(task)
```
Training the learner used 50 GB memory.

**Comment by be-marc** [comment] 2023-02-15 18:43
You can also try this code.

```r
afs = auto_fselector(
  learner = learner,
  resampling = rsmp("cv", folds = 3),
  measure = msr("classif.ce"),
  terminator = trm("evals", n_evals = 10),
  method = "random_search"
)

rr = resample(task, afs, rsmp("cv", folds = 3))
``

**Comment by be-marc** [comment] 2023-02-15 18:52
The code above peaks at 16 GB memory usage for me. When the next resampling iteration starts, it uses again the same amount of memory. I will let it run and see if anything changes. But I suspect not. So sorry it looks like I can't reproduce your problem.

**Comment by be-marc** [comment] 2023-02-15 18:54
> Could it be that setting multiple threads for the learner on my dataset causes the issue? However, I do use the same call to use multiple threads for the learner with both the single model and the nested resampling so I am not sure how that could be the cause of the discrepancy.

No I think not. I also use 40 threads now to fit the model. The only thing I can think of that could use more RAM is a parallelization with `future`.

**Comment by be-marc** [comment] 2023-02-15 18:56
You could try to run the code in a standard R console instead of RStudio.

**Comment by awaldman000** [comment] 2023-02-15 19:21
> Nested resampling also does not allocate more than 8 GB of memory.
> 
> ```r
> afs = auto_fselector(
>   learner = learner,
>   resampling = rsmp("cv", folds = 3),
>   measure = msr("classif.ce"),
>   terminator = trm("evals", n_evals = 10),
>   method = "random_search"
> )
> 
> rr = resample(tsk("spam"), afs, rsmp("cv", folds = 3))
> ```

In this call, store_models isn't set so is that something that is taken care of by the custom learner? I'm just trying to pinpoint the differences between what I'm doing with my data and this test. 

Could it be that I'm using repeated_cv rather than just cv?

**Comment by awaldman000** [comment] 2023-02-15 19:22
> You can also try this code.
> 
> ```r
> library(mlr3fselect)
> 
> afs = auto_fselector(
>   learner = learner,
>   resampling = rsmp("cv", folds = 3),
>   measure = msr("classif.ce"),
>   terminator = trm("evals", n_evals = 10),
>   method = "random_search"
> )
> 
> rr = resample(task, afs, rsmp("cv", folds = 3))
> ```

Should I try this with the OML learner or the custom learner at the top of the thread?

**Comment by be-marc** [comment] 2023-02-16 15:22
> Should I try this with the OML learner or the custom learner at the top of the thread?

You should try this with the ranger learner.

```r
library(mlr3oml)
library(mlr3learners)
library(mlr3fselect)

task = tsk("oml", data_id = 150)
learner = lrn("classif.ranger", num.trees = 10000, num.threads = 40)

afs = auto_fselector(
  learner = learner,
  resampling = rsmp("cv", folds = 3),
  measure = msr("classif.ce"),
  terminator = trm("evals", n_evals = 10),
  method = "random_search"
)

rr = resample(task, afs, rsmp("cv", folds = 3))
```

**Comment by awaldman000** [comment] 2023-02-16 17:18
> 

Nope this seems to run fine. I did notice that the messages were different than when I run my data. I don't see the following typically:

Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 54 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 16 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 34 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 8 minutes, 56 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 8 minutes, 21 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 7 minutes, 49 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 7 minutes, 17 seconds.

It is just so odd that the memory issue seems to only occur using my datasets?

**Comment by be-marc** [comment] 2023-02-16 19:10
I tried this script now that should be equal to your example except from the task.

```r
library(mlr3oml)
library(mlr3learners)
library(mlr3fselect)

task = tsk("oml", data_id = 150)
learner = lrn("classif.ranger", num.trees = 10000, num.threads = 40, importance = "impurity")
measure = msr("classif.fbeta", beta = 1, average="micro")

afs = auto_fselector(
  learner = learner,
  resampling = rsmp("repeated_cv", folds = 10, repeats = 10),
  measure = msr("classif.fbeta", beta = 1, average="micro"),
  terminator = trm("evals", n_evals = 10),
  method = fs("rfe", n_features = 1, feature_fraction = 0.5, recursive = FALSE)
)

rr = resample(task, afs, rsmp("repeated_cv", folds = 10, repeats = 10))
```

Still works without crashing. Does your script even create one model or does it crash on the first one? If not you could try a [fallback learner](https://mlr3book.mlr-org.com/optimization.html#sec-encapsulation-fallback). You could analyze the failing resampling splits afterwards. However, this will fail if you cannot create the first model because the you need the importance vector.

**Comment by awaldman000** [comment] 2023-02-17 00:44
> 

Iter 1/100 finishes and uses ~50GB. It dropped back down and is moving to iter 2/100. I will let it continue running to see what happens. With my data, I typically see a precipitous increase (never an increase then decrease back down to baseline once the next iter starts).

**Comment by awaldman000** [comment] 2023-02-17 11:07
I am at iter 11/100 since beginning and see that ~75GB is currently being used. I'm assuming that the memory shouldn't be creeping above the 50GB that was used in the first iteration? It is also going quite slowly but not sure if this is expected given the data size and lack of parallelization?

**Comment by be-marc** [comment] 2023-02-17 12:20
> I am at iter 11/100 since beginning and see that ~75GB is currently being used. I'm assuming that the memory shouldn't be creeping above the 50GB that was used in the first iteration.

When the final model is fitted after 10 iterations, the `AutoFSelector` uses the complete training set of the outer resampling, so the memory usage should be higher.

**Comment by be-marc** [comment] 2023-02-17 12:28
I just checked the size of the random forest model. The size is not 30 megabytes but multiple gigabytes. When you use a 10-fold cv in rfe, you need enough memory to store 9 models and have enough memory for the fitting process of the tenth model. The 128GB of your workbench might be not enough.

**Closed** 2023-02-17 12:30 UTC
